[tox]
isolated_build = true
envlist = py310,py311,py312,py313

[env_run_base]
set_env = { PYTHONPATH = "/Users/sholden/Projects/Python/hu/src" }

[testenv]
allowlist_externals =
    uv
commands =
    uv build
    uv run pytest tests -v --cov=hu --cov-report=term-missing
